# Generated by Django 2.2.7 on 2019-11-09 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound', models.TextField()),
                ('inbound', models.TextField()),
                ('roundTrip', models.BooleanField()),
                ('price', models.FloatField()),
                ('emissions', models.FloatField()),
                ('outboundDate', models.TextField()),
                ('inboundDate', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
